version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
environment:
  github_token: 'secure: fHV/gr0ZsTCsP6jPh2iNcWWybr2a6cRqdhTS5/hpKqFoWb2ixXAO+Ob9Y78B6kiI'
  myget_token: 'secure: 9Z+KYPk2hI7hg9kYLv/N13fvoqcYCP96isNUkRrKu0v87cw85H62oe/DCwpqvBXF'

init:
  - set PATH=C:\Program Files\Java\jdk21\bin;%PATH%
  - set JAVA_HOME_11_X64=C:\Program Files\Java\jdk21
  - set JAVA_HOME=C:\Program Files\Java\jdk21

install:
- ps: dotnet tool install --global GitVersion.Tool --version 5.*
- ps: dotnet tool install --global dotnet-sonarscanner
- cmd: nuget sources add -Name EPiServerFeed -Source https://nuget.optimizely.com/feed/packages.svc/

before_build:
- cmd: nuget restore
- ps: dotnet-gitversion /l console /output buildserver

build_script:
  - dotnet sonarscanner begin /k:"jstemerdink:EPi.Libraries.Logging.Serilog.Enrichers" /n:"EPi.Libraries.Logging.Serilog.Enrichers" /d:"sonar.host.url=https://sonarcloud.io" /o:"jstemerdink-github" /d:"sonar.login=0b0eec6902ab7d776899f79bfeff15d313dd6e09"
  - dotnet build "EPi.Libraries.Logging.Serilog.Enrichers.sln" --no-restore -c Release -p:Version=%GitVersion_MajorMinorPatch% -p:AssemblyVersion=%GitVersion_AssemblySemVer% -p:FileVersion=%GitVersion_AssemblySemFileVer% -p:ProductVersion=%GitVersion_MajorMinorPatch%
  - dotnet pack "EPi.Libraries.Logging.Serilog.Enrichers.sln" --no-build -c Release -p:PackageVersion=%GitVersion_NuGetVersion%
  - dotnet sonarscanner end /d:"sonar.login=0b0eec6902ab7d776899f79bfeff15d313dd6e09"

after_build:
- cmd: appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\EPi.Libraries.Logging.Serilog.Enrichers.Cms\bin\Release\EPi.Libraries.Logging.Serilog.Enrichers.Cms.%GitVersion_NuGetVersion%.nupkg"
- cmd: appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\EPi.Libraries.Logging.Serilog.Enrichers.Commerce\bin\Release\EPi.Libraries.Logging.Serilog.Enrichers.Commerce.%GitVersion_NuGetVersion%.nupkg"
- 7z a EPi.Libraries.Logging.Serilog.Enrichers.Cms.%GitVersion_NuGetVersion%.zip %APPVEYOR_BUILD_FOLDER%\EPi.Libraries.Logging.Serilog.Enrichers.Cms\bin\Release\bin\Release\*\*.dll
- cmd: appveyor PushArtifact "EPi.Libraries.Logging.Serilog.Enrichers.Cms.%GitVersion_NuGetVersion%.zip"
- 7z a EPi.Libraries.Logging.Serilog.Enrichers.Commerce.%GitVersion_NuGetVersion%.zip %APPVEYOR_BUILD_FOLDER%\EPi.Libraries.Logging.Serilog.Enrichers.Commerce\bin\Release\bin\Release\*\*.dll
- cmd: appveyor PushArtifact "EPi.Libraries.Logging.Serilog.Enrichers.Commerce.%GitVersion_NuGetVersion%.zip"

before_package:
- ps: >-
    Write-Host -NoNewline "Installing NuGet 3.3.0..."

    if (Test-Path 'C:\Tools\NuGet3') { $nugetDir = 'C:\Tools\NuGet3' } else { $nugetDir = 'C:\Tools\NuGet' }
deploy:
- provider: NuGet
  server: https://www.myget.org/F/epi-libraries/api/v2/package
  api_key:
    secure: 9Z+KYPk2hI7hg9kYLv/N13fvoqcYCP96isNUkRrKu0v87cw85H62oe/DCwpqvBXF
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: develop             # release from develop branch only
    #appveyor_repo_tag: true     # deploy on tag push only
- provider: GitHub
  auth_token:
    secure: fHV/gr0ZsTCsP6jPh2iNcWWybr2a6cRqdhTS5/hpKqFoWb2ixXAO+Ob9Y78B6kiI
  artifact: /.*\.zip/
  on:
    branch: master              # release from master branch only
    #appveyor_repo_tag: true     # deploy on tag push only